# Generated by Django 3.1.14 on 2024-04-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MazevoRoomSpace',
            fields=[
                ('room_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('space_id', models.PositiveIntegerField(default=None, null=True, unique=True)),
                ('date_changed', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
