# Generated by Django 3.1.14 on 2024-04-25 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mazevo_r25', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MazevoStatusMap',
            fields=[
                ('status_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('action', models.SlugField(choices=[('ignore', 'Neither add nor remove from R25'), ('remove', 'Remove if present in R25'), ('add', 'Add if not present in R25')], null=True)),
                ('event_type_id', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
