# Generated by Django 3.1.14 on 2024-07-16 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mazevo_r25', '0002_mazevostatusmap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mazevostatusmap',
            name='event_type_id',
            field=models.IntegerField(null=True),
        ),
    ]
