name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 coverage
        pip install -e .
    - name: Setup Django Project
      run: |
        django-admin startproject testproj .
        cp conf/urls.py testproj/
        cp conf/settings.py testproj/
        python manage.py migrate
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # uses settings in setup.cfg
        flake8 . --count --statistics
    - name: Run Tests
      run: |
        python manage.py test
